list: ~/plugins/hjfigueira/projetos/models/projeto/columns.yaml
modelClass: Hjfigueira\Projetos\Models\Projeto
title: Projetos
noRecordsMessage: 'backend::lang.list.no_records'
# showSetup: true
# showCheckboxes: true
toolbar:
   buttons: list_toolbar
#     search:
#         prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hjfigueira/projetos/details/index/:id'
